application: simple-push-demo
version: v2015-03-12
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  secure: always
  script: redirect.app

- url: /send_push
  secure: always
  script: main-old.app

- url: /api/v2/sendpush
  secure: always
  script: main-v2.app

- url: .*
  secure: always
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

skip_files:
- ^.git/.*$
